# Generated by Django 4.1.6 on 2023-02-13 21:58

import blog.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images/'), upload_to='blog-images/', validators=[blog.models.validate_image])),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_images',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_images',
            field=models.ManyToManyField(related_name='post_images', to='blog.image'),
        ),
    ]
