# Generated by Django 4.1.6 on 2023-02-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image_remove_blogpost_post_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='BlogPostImage',
        ),
    ]
