# Generated by Django 4.1.6 on 2023-02-20 12:00

import blog.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='space-our-resume/media'), upload_to='blog-images/', validators=[blog.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='images',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='space-our-resume/media'), upload_to='blog-images/', validators=[blog.models.validate_image]),
        ),
    ]
