# Generated by Django 4.1.6 on 2023-02-21 18:55

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='comment_id',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(upload_to='blog-images/', validators=[blog.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='blog-images/', validators=[blog.models.validate_image]),
        ),
    ]
