# Generated by Django 4.1.6 on 2023-02-13 22:33

import blog.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_image_blogpostimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostimage',
            name='image_links',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/images/'), upload_to='blog-images/', validators=[blog.models.validate_image]),
        ),
    ]
