# Generated by Django 4.1.6 on 2023-02-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpostimage_image_links_alter_blogpostimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_images',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_post_images',
            field=models.ManyToManyField(related_name='blog_post_images', to='blog.blogpostimage'),
        ),
    ]
