# Generated by Django 4.1.6 on 2023-02-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogpost_blog_post_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='image_links',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
