# Generated by Django 4.1.6 on 2023-02-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpostimage_image_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostimage',
            old_name='image',
            new_name='images',
        ),
    ]
