# Generated by Django 4.1.6 on 2023-02-13 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_image_blogpostimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostimage',
            old_name='images',
            new_name='imagesd',
        ),
    ]
