# Generated by Django 4.1.6 on 2023-02-13 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_images_blogpostimage_imagesd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostimage',
            old_name='imagesd',
            new_name='images',
        ),
    ]
