# Generated by Django 4.1.6 on 2023-02-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_imagesd_blogpostimage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostimage',
            name='image_links',
        ),
    ]
