# Generated by Django 4.1.6 on 2023-02-21 19:40

import UserManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=UserManagement.models.get_default_profile_image, null=True, upload_to='profile-images/', validators=[UserManagement.models.validate_image]),
        ),
    ]
