# Generated by Django 4.1.6 on 2023-02-22 00:04

import UserManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images/', validators=[UserManagement.models.validate_image]),
        ),
    ]
