# Generated by Django 4.1.6 on 2023-02-21 23:36

import UserManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://our-space.nyc3.digitaloceanspaces.com/space-our-resume%2Fmedia%2Favatar-images%2Favatar-male.jpg', null=True, upload_to='profile-images/', validators=[UserManagement.models.validate_image]),
        ),
    ]
