# Generated by Django 4.1.6 on 2023-03-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_active_status_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
    ]
